<a href="https://colab.research.google.com/github/JunginDo/class2021Spring/blob/main/20210426-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
%matplotlib inline
from matplotlib import pyplot as plt
import IPython.display as ipd
import numpy as np
from scipy.signal import lfilter

In [39]:
def phasor(amp, sr, dur, freq):
  return (np.arange(1, sr * dur+1)/sr, np.arange(1, sr * dur+1)* 2*np.pi * freq, np.sin(np.arange(1, sr * dur+1) * 2*np.pi * freq))




In [40]:
phasor (1, 10000, 0.5, 100.0)


(array([1.000e-04, 2.000e-04, 3.000e-04, ..., 4.998e-01, 4.999e-01,
        5.000e-01]),
 array([6.28318531e+02, 1.25663706e+03, 1.88495559e+03, ...,
        3.14033602e+06, 3.14096434e+06, 3.14159265e+06]),
 array([ 3.92877345e-15,  7.85754689e-15, -1.01900517e-13, ...,
        -3.51610461e-11, -1.29176132e-10, -2.23191218e-10]))